version: '3.8'

services:
  login:
    build:
      context: ./login-service
    container_name: login-service
    ports:
      - "8000:8000"

  db:
    build:
      context: ./db-service
    container_name: db-service
    ports:
      - "8001:8000"

  product:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8002:8000"

  payment:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8003:8000"
    depends_on:
      - db
      - product
      - login
